---
- hosts: Ubuntu
  become: true
  roles:
    - elasticsearch
    - filebeat
    - java
    - kibana
    - metricbeat

- hosts: CentOS
  become: true
  roles:
    - elasticsearch_centos
    - kibana_centos
    - metricbeat_centos
    - nginx
